name: 'Close Threads'

on:
  schedule:
    - cron: '50 20 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: close-threads

jobs:
  close-threads:
    if: github.repository_owner == 'jertel'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: 180
          days-before-issue-close: 365
          stale-issue-message: "This issue is stale because it has been open for 6 months with no activity. Stale issues convey that the issue, while important to someone, is not critical enough for the author, or other community members to work on, sponsor, or otherwise shepherd the issue through to a resolution."
          close-issue-message: "This issue was closed because it has been inactive for over a year since being marked as stale. It will be automatically locked after an additional 30 days, after which no further commenting will be available."
          days-before-pr-stale: 30
          days-before-pr-close: 30
          stale-pr-message: "This PR is stale because it has been open for 30 days with no activity. The longer a PR remains stale the more out of date with the main branch it becomes."
          close-pr-message: "This PR was closed because it has been inactive for 30 days since being marked as stale. It will be automatically locked after an additional 30 days. If there is still a commitment to finishing this PR please re-open it, or request that a project maintainer re-open it before it becomes locked."
          exempt-assignees: jertel
